#
# Copyright (C) 2024 nosignals
#
name: Building Rakitiw

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Prerelease ?'
        required: true
        default: false
        type: boolean
        
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: Build Rakitiw
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 21.02.7
          - 23.05.0
        arch:
          - x86_64
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get PKG_VERSION from Makefile
        id: vars
        run: echo "::set-output name=version::$(grep 'PKG_VERSION:=' Makefile | cut -d '=' -f2)"

      - name: Preparing Rakitiw
        run: |
              echo ""
              mkdir feeds artifacts
              find . -mindepth 1 -maxdepth 1 ! -name 'feeds' -exec cp -r {} feeds/ \;
        
      - name: Building Luci Rakitiw
        uses: nosignals/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-app-rakitiw
          NO_SHFMT_CHECK: 1
        
      - name: Delivering Package
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-rakitiw-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-app-rakitiw*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v3
        
      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./release
          cp -rf ./luci-app-rakitiw-21.02.7_x86_64/* ./release/luci-app-rakitiw_${{ steps.vars.outputs.version }}_all_21_02.ipk
          cp -rf ./luci-app-rakitiw-23.05.0_x86_64/* ./release/luci-app-rakitiw_${{ steps.vars.outputs.version }}_all_23_05.ipk
  
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          overwrite: true
          prerelease: ${{ inputs.prerelease }}
          tag: ${{ steps.vars.outputs.version }}
          file_glob: true
          body: |
            # LUCI APP RAKITIW ${{ steps.vars.outputs.version }}