name: Building Rakitiw - Dev

on:
  push:
    paths:
      - 'luci-app-rakitiw/Makefile'
    branches:
      - dev
  repository_dispatch:
  workflow_dispatch:
        
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: Build Rakitiw
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 21.02.7
          - 23.05.0
        arch:
          - x86_64
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: dev
      
      - name: Get PKG_VERSION from Makefile
        id: vars
        run: echo "::set-output name=version::$(grep 'PKG_VERSION:=' Makefile | cut -d '=' -f2)"

      - name: Preparing Rakitiw
        run: |
              echo ""
              mkdir feeds artifacts
              cp -rf ./luci-app-rakitiw ./feeds
              echo "DATETIME=$(date +'%Y.%m.%d-%H:%M:%S')" >> $GITHUB_ENV
        
      - name: Building Luci App Rakitiw
        uses: nosignals/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-app-rakitiw
          NO_SHFMT_CHECK: 1
        
      - name: Delivering Package
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-rakitiw-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-app-rakitiw*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v3
        
      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./release
          cp -rf ./luci-app-rakitiw-21.02.7_x86_64/* ./release/luci-app-rakitiw_${{ steps.vars.outputs.version }}_all_21_02.ipk
          cp -rf ./luci-app-rakitiw-23.05.0_x86_64/* ./release/luci-app-rakitiw_${{ steps.vars.outputs.version }}_all_23_05.ipk
  
      - name: Add changelog info to new release description
        id: changelog
        shell: bash
        run: |
          r=$(awk '/^\*\*Changelog\*\*/ {if(found) exit; found=1} found' CHANGELOG.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"  
          echo "CHANGELOG=$r" >> $GITHUB_OUTPUT

      - name: Upload Firmware to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./release/*
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: "${{ steps.vars.outputs.version }}-beta"
          release_name: "Luci App Rakitiw Version - ${{ steps.vars.outputs.version }} - ${{ env.DATETIME }}"
          prerelease: true
          overwrite: true
          body: |
            Build date: ${{ env.DATETIME }} For Version : ${{ steps.vars.outputs.version }}
        
            ${{ steps.changelog.outputs.CHANGELOG }}

            ![GitHub Downloads (all assets, specific tag)](https://img.shields.io/github/downloads/rtaserver/luci-app-rakitiw/${{ steps.vars.outputs.version }}/total?style=for-the-badge&logo=openwrt&label=Download&color=blue)

            ---
            INFORMATION TESTED
            ---
            #### Modem Rakitan:
            * Dell Dw5821e
            * Fibocom L850 GL
            * Fibocom L860 GL
          
            #### Modem HP:
            * Semua Tipe HP Root / Non Root
            > Jangan Lupa USB Debugging Aktif
          
            #### Modem Huawei / Orbit:
            * Huawei B310s-22
            * Huawei B312-926
            * Huawei B315s-22
            * Huawei B525s-23a
            * Huawei B525s-65a
            * Huawei B715s-23c
            * Huawei B528s
            * Huawei B535-232
            * Huawei B628-265
            * Huawei B612-233
            * Huawei B818-263
            * Huawei E5186s-22a
            * Huawei E5576-320
            * Huawei E5577Cs-321
            * Huawei E8231
            * SoyeaLink B535-333
            * Huawei E3131
            * Huawei E3372
            * Huawei E3531
            * Huawei 5G CPE Pro 2 (H122-373)
            * Huawei 5G CPE Pro (H112-372)
          
            (probably will work for other Huawei LTE devices too)
            ---
            INSTALL & UPGRADE
            ---
            
            ![Tutor Install](https://github.com/rtaserver/luci-app-rakitiw/assets/142883865/1694190b-c025-4855-a77d-8212fab27564)

            1. Upload File IPK Ke Folder Root (biar gampang)
            2. Buka / Akses Terminal Openwrt
            3. Stop Dan Hapus `luci-app-rakitiw` dahulu Jalankan di Terminal. Jika Fresh Install Bisa Skip Ini Lanjut No 4
            ```
            $ /etc/init.d/rakitiw stop
            $ opkg remove luci-app-rakitiw
            ```
            4. Setelah Terhapus Jalankan Kembali Perintah ini di Terminal
            ```
            $ opkg update
            $ cd /root
            $ opkg install luci-app-rakitiw*.ipk
            ```
            5. Tunggu Hingga Proses Instalasi Selesai. *Pastika Ada Koneksi Internet*
            6. Jika Gagal Install Atau Upgrade Coba Update Depends Secara Manual
            ```
            $ opkg update
            $ opkg install modemmanager
            $ opkg install python3-pip
            $ pip3 install requests
            $ pip3 install huawei-lte-api
            $ opkg install luci-app-rakitiw*.ipk --force-reinstall
            ```
            7. Jika Proses Instalasi Berhasil Buka Modem Rakitan Di Tab Modem
            8. Atau Bisa : http://192.168.1.1/rakitiw - Sesuaikan Dengan IP OpenWrt

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1