#
# Copyright (C) 2024 nosignals
#
name: Building Rakitiw

on:
  workflow_dispatch:
        
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: Build Rakitiw
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 21.02.7
          - 23.05.0
        arch:
          - x86_64
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get PKG_VERSION from Makefile
        id: pkg_version
        run: echo "::set-output name=version::$(grep 'PKG_VERSION:=' Makefile | cut -d '=' -f2)"

      - name: Preparing Rakitiw
        run: |
              echo ""
              mkdir feeds artifacts
              cp -rf ./* ./feeds
        
      - name: Building Luci Rakitiw
        uses: nosignals/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-app-rakitiw
          NO_SHFMT_CHECK: 1
        
      - name: Delivering Package
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-rakitiw-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-app-rakitiw*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v3
        
      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./release
          cp -rf ./luci-app-rakitiw-21.02.7_x86_64/* ./release/luci-app-rakitiw_${{ steps.pkg_version.outputs.version }}_all_21_02.ipk
          cp -rf ./luci-app-rakitiw-23.05.0_x86_64/* ./release/luci-app-rakitiw_${{ steps.pkg_version.outputs.version }}_all_23_05.ipk
  
      - name: Add changelog info to new release description
        id: changelog
        shell: bash
        run: |
          r=$(awk '/^\*\*Changelog\*\*/ {if(found) exit; found=1} found' CHANGELOG.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"  
          echo "CHANGELOG=$r" >> $GITHUB_OUTPUT

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          overwrite: true
          tag: ${{ steps.pkg_version.outputs.version }}
          file_glob: true
          body: |
            # LUCI APP RAKITIW ${{ steps.pkg_version.outputs.version }}
            Simple Mange Modem Rakitan
            ### Informasi
            - Changelog : 
              - ${{ steps.changelog.outputs.CHANGELOG }}
            ### Beberapa Dependensi Yang Di Butuhkan
            - ` bash, php, php-cgi curl `
            - OpenWrt 21: ` php7 php7-cgi bash`
            - Openwrt 23: ` php8 php8-cgi bash` 