name: Build New IPK Dev

on:
  push:
    paths:
      - 'Makefile'
    branches:
      - dev
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Jakarta
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  job_build_rta:
    name: Build RTA (dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Get PKG_VERSION from Makefile
        id: vars
        run: echo "::set-output name=version::$(grep 'PKG_VERSION:=' Makefile | cut -d '=' -f2)"

      - name: Reading Package 
        id: list_package
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: dev
          path: list_packages.txt

      - name: Install packages
        run: |
          echo "Install packages"
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev git-core subversion gettext unzip zlib1g-dev file perl libssl-dev wget

      - name: Initialization environment
        env:
          url_sdk: https://archive.openwrt.org/releases/21.02.5/targets/x86/64/openwrt-sdk-21.02.5-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        run: |
          wget ${{ env.url_sdk }}
          file_name=$(echo ${{env.url_sdk}} | awk -F/ '{print $NF}')
          mkdir sdk && tar -xJf $file_name -C ./sdk --strip-components=1
          cd sdk  
          echo "src-git base https://github.com/openwrt/openwrt.git;openwrt-21.02" > feeds.conf
          echo "src-git-full packages https://github.com/openwrt/packages.git;openwrt-21.02" >> feeds.conf
          echo "src-git-full luci https://git.openwrt.org/project/luci.git;openwrt-21.02" >> feeds.conf
          echo "src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-21.02"  >> feeds.conf
          git clone --branch dev "https://github.com/${{ github.repository }}.git" package/downloads/luci-app-rakitiw

          ./scripts/feeds update -a
          for package in ${{ steps.list_package.outputs.content}}; do
            ./scripts/feeds install -d n "$package"
          done

      - name: Configure RTA (dev)
        run: |
          cd sdk
          for package in ${{ steps.list_package.outputs.content}}; do
            ./scripts/feeds install "$package"
          done
          make defconfig

      - name: Compile RTA (dev)
        id: compile
        run: |
          cd sdk
          for package in ${{ steps.list_package.outputs.content}}; do
            make "package/$package/compile"
          done
          mv bin/packages/x86_64/base/ ../
          cd ..
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y.%m.%d-%H:%M:%S')" >> $GITHUB_ENV

      - name: Add changelog info to new release description
        id: changelog
        shell: bash
        run: |
          r=$(awk '/^\*\*Changelog\*\*/ {if(found) exit; found=1} found' CHANGELOG.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"  
          echo "CHANGELOG=$r" >> $GITHUB_OUTPUT

      - name: Upload Firmware to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ env.FIRMWARE }}/base/*.ipk
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: "${{ steps.vars.outputs.version }}-beta"
          release_name: "Luci App Rakitiw Version - ${{ github.event.repository.name }} - ${{ env.DATETIME }}"
          prerelease: true
          overwrite: true
          body: |
            Build date: ${{ env.DATETIME }} For Version : ${{ github.event.repository.name }}
        
            ${{ steps.changelog.outputs.CHANGELOG }}

            ![GitHub Downloads (all assets, specific tag)](https://img.shields.io/github/downloads/rtaserver/luci-app-rakitiw/${{ steps.vars.outputs.version }}/total?style=for-the-badge&logo=openwrt&label=Download&color=blue)

            ---
            INFORMATION TESTED
            ---
            #### Modem Rakitan:
            * Dell Dw5821e
            * Fibocom L850 GL
            * Fibocom L860 GL
          
            #### Modem HP:
            * Semua Tipe HP Root / Non Root
            > Jangan Lupa USB Debugging Aktif
          
            #### Modem Huawei / Orbit:
            * Huawei B310s-22
            * Huawei B312-926
            * Huawei B315s-22
            * Huawei B525s-23a
            * Huawei B525s-65a
            * Huawei B715s-23c
            * Huawei B528s
            * Huawei B535-232
            * Huawei B628-265
            * Huawei B612-233
            * Huawei B818-263
            * Huawei E5186s-22a
            * Huawei E5576-320
            * Huawei E5577Cs-321
            * Huawei E8231
            * SoyeaLink B535-333
            * Huawei E3131
            * Huawei E3372
            * Huawei E3531
            * Huawei 5G CPE Pro 2 (H122-373)
            * Huawei 5G CPE Pro (H112-372)
          
            (probably will work for other Huawei LTE devices too)
            ---
            INSTALL & UPGRADE
            ---
            
            ![Tutor Install](https://github.com/rtaserver/luci-app-rakitiw/assets/142883865/1694190b-c025-4855-a77d-8212fab27564)

            1. Upload File IPK Ke Folder Root (biar gampang)
            2. Buka / Akses Terminal Openwrt
            3. Stop Dan Hapus `luci-app-rakitiw` dahulu Jalankan di Terminal. Jika Fresh Install Bisa Skip Ini Lanjut No 4
            ```
            $ /etc/init.d/rakitiw stop
            $ opkg remove luci-app-rakitiw
            ```
            4. Setelah Terhapus Jalankan Kembali Perintah ini di Terminal
            ```
            $ opkg update
            $ cd /root
            $ opkg install luci-app-rakitiw*.ipk
            ```
            5. Tunggu Hingga Proses Instalasi Selesai. *Pastika Ada Koneksi Internet*
            6. Jika Gagal Install Atau Upgrade Coba Update Depends Secara Manual
            ```
            $ opkg update
            $ opkg install modemmanager
            $ opkg install python3-pip
            $ pip3 install requests
            $ pip3 install huawei-lte-api
            $ opkg install luci-app-rakitiw*.ipk --force-reinstall
            ```
            7. Jika Proses Instalasi Berhasil Buka Modem Rakitan Di Tab Modem
            8. Atau Bisa : http://192.168.1.1/rakitiw - Sesuaikan Dengan IP OpenWrt

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1